# working on numpy

In [47]:
#importing numpy as np
import numpy as np

### creating an array of different dimensions

In [51]:
o=np.array(69)#zero dimention
t=np.array([1,2,3,2,5,6])#one dimention
m=np.array([[[1,2],[3,6]],[[4,5],[6,9]]])#multi dimentional

### printing dimentions, type and array

In [52]:
print(type(o))
print(m.ndim)
print(t)
print(m)

<class 'numpy.ndarray'>
3
[1 2 3 2 5 6]
[[[1 2]
  [3 6]]

 [[4 5]
  [6 9]]]


In [53]:
res=np.asarray(t,dtype="float")

In [54]:
res

array([1., 2., 3., 2., 5., 6.])

In [55]:
res1=np.asarray(m,dtype="str",order="F")
res1

array([[['1', '2'],
        ['3', '6']],

       [['4', '5'],
        ['6', '9']]], dtype='<U11')

In [56]:
for i in res1:
    print(i)

[['1' '2']
 ['3' '6']]
[['4' '5']
 ['6' '9']]


In [57]:
for i in res1:
    for j in i:
        print(j)

['1' '2']
['3' '6']
['4' '5']
['6' '9']


### working on nditer

In [58]:
for i in np.nditer(res1):
    for j in np.nditer(i):
        print(j)

1
4
3
6
2
5
6
9


### using frombuffer(buffer,dtype,count,offset) 

In [59]:
s=b'welcom'
c=np.frombuffer(s,dtype='S1',count=4,offset=2)
print(c)
print(s)

[b'l' b'c' b'o' b'm']
b'welcom'


In [60]:
c=np.frombuffer(s,dtype='S1',count=6,offset=0)
print(c)

[b'w' b'e' b'l' b'c' b'o' b'm']


In [61]:
print(help(np.frombuffer))

Help on built-in function frombuffer in module numpy:

frombuffer(...)
    frombuffer(buffer, dtype=float, count=-1, offset=0, *, like=None)
    
    Interpret a buffer as a 1-dimensional array.
    
    Parameters
    ----------
    buffer : buffer_like
        An object that exposes the buffer interface.
    dtype : data-type, optional
        Data-type of the returned array; default: float.
    count : int, optional
        Number of items to read. ``-1`` means all data in the buffer.
    offset : int, optional
        Start reading the buffer from this offset (in bytes); default: 0.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionadded:: 

### using fromiter(iter,dtype,count)

In [62]:
l=[97,98,99]
q=np.fromiter(l,dtype="S3",count=3)
print(q)

[b'97' b'98' b'99']


### using arange (start index,stopindex,step,dtype) similar to range function with pyhon

In [64]:
np.arange(0,20,2,dtype="int")

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [63]:
arr=np.arange(0,20,2,dtype="float")
print(arr)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]


### using linspace(start,stop,num=50,endpoint=50,retstep=False,dtype)

In [66]:
arr1=np.linspace(0,30,9,endpoint=False,retstep=True)
print(arr1)

(array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667]), 3.3333333333333335)


In [71]:
#using defalut values
arr2=np.linspace(1,50)
print(arr2)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]


### using logspace(start,stop,num,endpoint=True,base=10,dtype)

In [80]:
#using defalut values
arr3=np.logspace(0,10)
print(arr3)

[1.00000000e+00 1.59985872e+00 2.55954792e+00 4.09491506e+00
 6.55128557e+00 1.04811313e+01 1.67683294e+01 2.68269580e+01
 4.29193426e+01 6.86648845e+01 1.09854114e+02 1.75751062e+02
 2.81176870e+02 4.49843267e+02 7.19685673e+02 1.15139540e+03
 1.84206997e+03 2.94705170e+03 4.71486636e+03 7.54312006e+03
 1.20679264e+04 1.93069773e+04 3.08884360e+04 4.94171336e+04
 7.90604321e+04 1.26485522e+05 2.02358965e+05 3.23745754e+05
 5.17947468e+05 8.28642773e+05 1.32571137e+06 2.12095089e+06
 3.39322177e+06 5.42867544e+06 8.68511374e+06 1.38949549e+07
 2.22299648e+07 3.55648031e+07 5.68986603e+07 9.10298178e+07
 1.45634848e+08 2.32995181e+08 3.72759372e+08 5.96362332e+08
 9.54095476e+08 1.52641797e+09 2.44205309e+09 3.90693994e+09
 6.25055193e+09 1.00000000e+10]


In [91]:
arr3=np.logspace(0,100,4,endpoint=False,base=2,dtype="float")


In [92]:
print(arr3)

[1.00000000e+00 3.35544320e+07 1.12589991e+15 3.77789319e+22]


### INITIALIZING ARRAYS IN NUMPY ( ZEROS( ) ,ONES( ) ,FULL( ) ,EYE( ) FUNCTIONS ) 

In [94]:
a=np.array([5,6,9,3,4])
print(np.shape(a))

(5,)


In [95]:
m=np.array([[[1,2],[3,6]],[[4,5],[6,9]]])
print(np.shape(m))

(2, 2, 2)


In [97]:
print(np.reshape(m,(4,2)))

[[1 2]
 [3 6]
 [4 5]
 [6 9]]


In [99]:
print(np.shape(m))
print(np.reshape(m,(8,)))

(2, 2, 2)
[1 2 3 6 4 5 6 9]


#### Note: number of elements should match or should be constant 

In [108]:
# zeros matrix
z=np.zeros((5,5))
print(z)
z=np.zeros((2,3),dtype="int")
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0]
 [0 0 0]]


#### zeros(),ones() and full() works in a same way but in ones we will get all elements as ones and full() prints the array with given value

In [110]:
e=np.eye(6)
print(e)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


#### in eye function all diagonal elements are one and remaining elements are zeros as shown above

## indexing and slicing

### 1d array indexing similar to lists so lets see 2d and multi dimention array

In [115]:
td=np.array([[1,4,7],[2,5,8],[3,6,9]])
print(td[1,2])#prints 8 and kind of similar to lists but in same brackets here
print(td[2,1:])#prints [6,9] kind of similar to lists but in same brackets here
md=np.array([[[1,4],[4,7]],[[2,5],[5,8]],[[3,6],[6,9]]])
print(md[2,1,0])#prints 6 and  kind of similar to lists but in same brackets here
print(md[0,1,0:1])#prints [4] kind of similar to lists but in same brackets here
#you can also give step the syntax is [start:stop:step]

8
[6 9]
6
[4]


### data type in array

In [116]:
print(a.dtype)

int32


In [117]:
print(td.dtype)

int32


In [124]:
x=td.astype("F")# as type is to explictly change the data type 
print(x)

[[1.+0.j 4.+0.j 7.+0.j]
 [2.+0.j 5.+0.j 8.+0.j]
 [3.+0.j 6.+0.j 9.+0.j]]


In [127]:
y=td.astype("S")
print(y)

[[b'1' b'4' b'7']
 [b'2' b'5' b'8']
 [b'3' b'6' b'9']]


### copy vs view functions

In [141]:
w=y.copy()
print(y)

[[b'1' b'4' b'7']
 [b'2' b'5' b'8']
 [b'3' b'6' b'9']]


In [149]:
w=w.astype("i")
print(w)
print(y)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[b'1' b'4' b'7']
 [b'2' b'5' b'8']
 [b'3' b'6' b'9']]


In [152]:
print(w)
v=w.view()
v=v.astype("S")
print(v)
print(w)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[b'1' b'4' b'7']
 [b'2' b'5' b'8']
 [b'3' b'6' b'9']]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [153]:
print(w)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [154]:
v[1,2]=b"9"

In [159]:
print("v= ",v)
print("y= ",y)

v=  [[b'1' b'4' b'7']
 [b'2' b'5' b'9']
 [b'3' b'6' b'9']]
y=  [[b'1' b'4' b'7']
 [b'2' b'5' b'8']
 [b'3' b'6' b'9']]


### joining using concatenate((arr1,arr2),axis)

### stack(),vstack(),hstack(),dstack()

In [160]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [163]:
b=np.arange(10,28,2).reshape(3,3)
b

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

In [170]:
v=np.concatenate((a,b),axis=1)
v

array([[ 0,  1,  2, 10, 12, 14],
       [ 3,  4,  5, 16, 18, 20],
       [ 6,  7,  8, 22, 24, 26]])

In [169]:
v=np.concatenate((a,b),axis=0)
v

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

In [172]:
np.stack((a,b))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[10, 12, 14],
        [16, 18, 20],
        [22, 24, 26]]])

In [173]:
np.stack((a,b),axis=1)

array([[[ 0,  1,  2],
        [10, 12, 14]],

       [[ 3,  4,  5],
        [16, 18, 20]],

       [[ 6,  7,  8],
        [22, 24, 26]]])

In [175]:
vst=np.vstack((a,b))
print(vst)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 12 14]
 [16 18 20]
 [22 24 26]]


In [177]:
hst=np.hstack((a,b))
print(hst)

[[ 0  1  2 10 12 14]
 [ 3  4  5 16 18 20]
 [ 6  7  8 22 24 26]]


In [181]:
dst=np.dstack((a,b))
print(dst)
print(np.ndim(dst))

[[[ 0 10]
  [ 1 12]
  [ 2 14]]

 [[ 3 16]
  [ 4 18]
  [ 5 20]]

 [[ 6 22]
  [ 7 24]
  [ 8 26]]]
3


## arithimitic operations in numpy

In [185]:
a=np.array([[[1,2,3],[1,4,7]],[[2,5,8],[7,5,3]],[[1,5,9],[3,6,9]]])
b=np.arange(18,18*3,2).reshape(3,2,3)
print(b)
print(a)

[[[18 20 22]
  [24 26 28]]

 [[30 32 34]
  [36 38 40]]

 [[42 44 46]
  [48 50 52]]]
[[[1 2 3]
  [1 4 7]]

 [[2 5 8]
  [7 5 3]]

 [[1 5 9]
  [3 6 9]]]


In [186]:
np.shape(a)

(3, 2, 3)

In [187]:
np.shape(b)

(3, 2, 3)

## rules of broadcast.
### shape of two arrays must be equal as shown above.

In [188]:
np.add(a,b)

array([[[19, 22, 25],
        [25, 30, 35]],

       [[32, 37, 42],
        [43, 43, 43]],

       [[43, 49, 55],
        [51, 56, 61]]])

### rule2 second array must have at least one dimentionand no of elements in one row should be equal

In [190]:
c=np.array([5,3,8])

In [192]:
np.subtract(b,c)
#note the output :- the single row of c will be subtracted from every row of b

array([[[13, 17, 14],
        [19, 23, 20]],

       [[25, 29, 26],
        [31, 35, 32]],

       [[37, 41, 38],
        [43, 47, 44]]])

### rule three the second array can be a single value

In [195]:
d=np.array(25)
k=np.multiply(a,d)
print(k)
#note the single value is multiplied with each and every element.

[[[ 25  50  75]
  [ 25 100 175]]

 [[ 50 125 200]
  [175 125  75]]

 [[ 25 125 225]
  [ 75 150 225]]]


### some operations for complex numbers.

In [206]:
v=k.astype("F")
print(v)

[[[ 25.+0.j  50.+0.j  75.+0.j]
  [ 25.+0.j 100.+0.j 175.+0.j]]

 [[ 50.+0.j 125.+0.j 200.+0.j]
  [175.+0.j 125.+0.j  75.+0.j]]

 [[ 25.+0.j 125.+0.j 225.+0.j]
  [ 75.+0.j 150.+0.j 225.+0.j]]]


In [213]:
print(help(np.add))

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [214]:
np.real(v)#print real part of complex numbers

array([[[ 25.,  50.,  75.],
        [ 25., 100., 175.]],

       [[ 50., 125., 200.],
        [175., 125.,  75.]],

       [[ 25., 125., 225.],
        [ 75., 150., 225.]]], dtype=float32)

In [215]:
np.imag(v)

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [218]:
c = np.array([1+2j, 3-4j, 5+6j])
np.imag(c)# print(imaginary part

array([ 2., -4.,  6.])

In [219]:
np.conjugate(c)# change the sign for complex part

array([1.-2.j, 3.+4.j, 5.-6.j])

### stastical functions 

### functions amin() amax() average() mean() std()#standard deviation var() median() 

In [221]:
a=np.array([[1,2,3],[1,4,7],[2,5,8]])


### amin() amax()

In [225]:
print(np.amin(a,axis=0))#min elements of each coloum
print(np.amax(a,axis=1))#max elements of each coloum
print(np.amin(a))

[1 2 3]
[3 7 8]
1


### average()

In [227]:
print(np.average(a))

3.6666666666666665


In [228]:
w=[10,20,30]

In [232]:
print(np.average(a,weights=w,axis=0))#multiply the each element wrt coloum with the each element in w respectively and divide with sum of w

[1.5        4.16666667 6.83333333]


### mean() median()

In [233]:
np.mean(a)#similar to average

3.6666666666666665

In [234]:
np.mean(a,axis=0)

array([1.33333333, 3.66666667, 6.        ])

In [235]:
np.mean(a,axis=1)

array([2., 4., 5.])

In [237]:
print(a)
np.median(a)

[[1 2 3]
 [1 4 7]
 [2 5 8]]


3.0

In [238]:
np.median(a,axis=0)

array([1., 4., 7.])

In [239]:
np.median(a,axis=1)

array([2., 4., 5.])

In [241]:
np.var(a)#variance

5.777777777777778

In [243]:
np.std(a)#standard deviation

2.4037008503093262